version: '3.8'

services:
  frontend:
    container_name: DomoticAssistant-Frontend
    build: ./frontend
    command: "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/frontend
    ports:
      - 5768:5768

  backend:
    container_name: DomoticAssistant-Backend
    build: ./backend
    command: "npm run dev"
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
